server.port: ${PORT:8080}
spring:
  #Already specified in bootstrap.yml.
  #application.name: accounts-service
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/testdb
    username: root
    password: rootpass
  jpa:
    hibernate.ddl-auto: none
    show_sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        id:
          new_generator_mappings: false
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
    #Ribbon project is under maintenance, and as per Spring team's recommendation,
    #keeping the below flag as 'false' to exclude the default usage of Ribbon.
    #Sample warning from logs given below:
    #"BlockingLoadBalancerClientRibbonWarnLogger : You already have RibbonLoadBalancerClient on your classpath. 
    #It will be used by default. As Spring Cloud Ribbon is in maintenance mode. We recommend switching to BlockingLoadBalancerClient instead.
    #In order to use it, set the value of `spring.cloud.loadbalancer.ribbon.enabled` to `false` or 
    #remove spring-cloud-starter-netflix-ribbon from your project."
    loadbalancer.ribbon.enabled: false

#Enabling all endpoints, just for demo purposes
management.endpoints.web.exposure.include: '*'

#Application biz logic specific configurations:
create-account:
  min-age: 18          
